services:
  app:
    build: .
    container_name: curriculum-curator
    restart: unless-stopped
    ports:
      - "8081:80"  # FastAPI serves both API and frontend on port 80
    networks:
      - caddy_default
    volumes:
      # Persistent data - these directories will survive container restarts
      - ./data/db:/app/backend/data
      - ./data/uploads:/app/backend/uploads
      - ./data/logs:/app/backend/logs
      - ./data/content_repo:/app/backend/content_repo
    environment:
      # Database
      - DATABASE_URL=sqlite:///./data/curriculum_curator.db
      
      # Security (CHANGE THESE IN PRODUCTION!)
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this-in-production}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      
      # LLM API Keys (optional - users can configure in app)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      
      # Features
      - ENABLE_AI_FEATURES=${ENABLE_AI_FEATURES:-true}
      - ENABLE_FILE_UPLOAD=${ENABLE_FILE_UPLOAD:-true}
      - DEBUG=${DEBUG:-false}
      
      # Email (optional)
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:-}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Curriculum Curator}
      - SMTP_TLS=${SMTP_TLS:-true}
      
      # Frontend URL (update for your domain)
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8080}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  caddy_default:
    external: true