"""Initial migration with all models

Revision ID: 6917dd067586
Revises: 
Create Date: 2025-08-17 07:34:02.671314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.user import GUID


# revision identifiers, used by Alembic.
revision: str = '6917dd067586'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_whitelist',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_whitelist_id'), 'email_whitelist', ['id'], unique=False)
    op.create_index(op.f('ix_email_whitelist_pattern'), 'email_whitelist', ['pattern'], unique=True)
    op.create_table('login_attempts',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('attempt_type', sa.String(length=30), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('lockout_reason', sa.String(length=200), nullable=True),
    sa.Column('first_attempt', sa.DateTime(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempt_type'), 'login_attempts', ['attempt_type'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_is_locked'), 'login_attempts', ['is_locked'], unique=False)
    op.create_index(op.f('ix_login_attempts_locked_until'), 'login_attempts', ['locked_until'], unique=False)
    op.create_table('security_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_description', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('jwt_token_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('response_time_ms', sa.String(length=20), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('success', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_logs_event_type'), 'security_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_logs_id'), 'security_logs', ['id'], unique=False)
    op.create_index(op.f('ix_security_logs_ip_address'), 'security_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_security_logs_jwt_token_id'), 'security_logs', ['jwt_token_id'], unique=False)
    op.create_index(op.f('ix_security_logs_severity'), 'security_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_security_logs_timestamp'), 'security_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_logs_user_email'), 'security_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_security_logs_user_id'), 'security_logs', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('position_title', sa.String(length=255), nullable=True),
    sa.Column('teaching_philosophy', sa.String(length=50), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('teaching_preferences', sa.JSON(), nullable=True),
    sa.Column('llm_config', sa.JSON(), nullable=True),
    sa.Column('content_generation_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teaching_philosophy', sa.String(length=50), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('course_metadata', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('assessment_structure', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_user_id'), 'courses', ['user_id'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_code'), 'email_verifications', ['code'], unique=False)
    op.create_index(op.f('ix_email_verifications_id'), 'email_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('token', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_id'), 'password_resets', ['id'], unique=False)
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=False)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_table('system_config',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_category'), 'system_config', ['category'], unique=False)
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    op.create_table('units',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pedagogy_type', sa.String(length=30), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('owner_id', GUID(), nullable=False),
    sa.Column('created_by_id', GUID(), nullable=False),
    sa.Column('updated_by_id', GUID(), nullable=True),
    sa.Column('unit_metadata', sa.JSON(), nullable=True),
    sa.Column('generation_context', sa.Text(), nullable=True),
    sa.Column('credit_points', sa.Integer(), nullable=False),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('learning_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_code'), 'units', ['code'], unique=False)
    op.create_index(op.f('ix_units_created_by_id'), 'units', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_owner_id'), 'units', ['owner_id'], unique=False)
    op.create_index(op.f('ix_units_semester'), 'units', ['semester'], unique=False)
    op.create_index(op.f('ix_units_status'), 'units', ['status'], unique=False)
    op.create_index(op.f('ix_units_title'), 'units', ['title'], unique=False)
    op.create_index(op.f('ix_units_year'), 'units', ['year'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('context_scope', sa.String(length=20), nullable=False),
    sa.Column('context_content_ids', sa.JSON(), nullable=True),
    sa.Column('context_metadata', sa.JSON(), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_unit_id'), 'chat_sessions', ['unit_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('contents',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('unit_id', GUID(), nullable=False),
    sa.Column('parent_content_id', GUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('content_category', sa.String(length=20), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('validation_metadata', sa.JSON(), nullable=True),
    sa.Column('content_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_parent_content_id'), 'contents', ['parent_content_id'], unique=False)
    op.create_index(op.f('ix_contents_status'), 'contents', ['status'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_index(op.f('ix_contents_type'), 'contents', ['type'], unique=False)
    op.create_index(op.f('ix_contents_unit_id'), 'contents', ['unit_id'], unique=False)
    op.create_index(op.f('ix_contents_week_number'), 'contents', ['week_number'], unique=False)
    op.create_table('course_modules',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('course_id', GUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('pre_class_content', sa.JSON(), nullable=True),
    sa.Column('in_class_content', sa.JSON(), nullable=True),
    sa.Column('post_class_content', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('materials_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_modules_course_id'), 'course_modules', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_modules_id'), 'course_modules', ['id'], unique=False)
    op.create_table('course_outlines',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('credit_points', sa.Integer(), nullable=False),
    sa.Column('student_workload_hours', sa.Integer(), nullable=True),
    sa.Column('delivery_mode', sa.String(length=50), nullable=True),
    sa.Column('teaching_pattern', sa.Text(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('corequisites', sa.Text(), nullable=True),
    sa.Column('assumed_knowledge', sa.Text(), nullable=True),
    sa.Column('graduate_attributes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('created_by_id', GUID(), nullable=False),
    sa.Column('updated_by_id', GUID(), nullable=True),
    sa.Column('approved_by_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_outlines_id'), 'course_outlines', ['id'], unique=False)
    op.create_index(op.f('ix_course_outlines_unit_id'), 'course_outlines', ['unit_id'], unique=False)
    op.create_table('course_search_results',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=False),
    sa.Column('search_query', sa.String(length=500), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('processed_results', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('source_count', sa.JSON(), nullable=True),
    sa.Column('is_used_for_generation', sa.Boolean(), nullable=False),
    sa.Column('generation_context', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.JSON(), nullable=True),
    sa.Column('quality_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_search_results_id'), 'course_search_results', ['id'], unique=False)
    op.create_index(op.f('ix_course_search_results_search_query'), 'course_search_results', ['search_query'], unique=False)
    op.create_index(op.f('ix_course_search_results_unit_id'), 'course_search_results', ['unit_id'], unique=False)
    op.create_table('lrds',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('course_id', GUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('approval_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lrds_course_id'), 'lrds', ['course_id'], unique=False)
    op.create_index(op.f('ix_lrds_id'), 'lrds', ['id'], unique=False)
    op.create_table('assessment_plans',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('course_outline_id', GUID(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=True),
    sa.Column('assessment_name', sa.String(length=500), nullable=False),
    sa.Column('assessment_type', sa.String(length=30), nullable=False),
    sa.Column('assessment_mode', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight_percentage', sa.Float(), nullable=False),
    sa.Column('pass_mark', sa.Float(), nullable=True),
    sa.Column('release_week', sa.Integer(), nullable=True),
    sa.Column('due_week', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('submission_format', sa.String(length=100), nullable=True),
    sa.Column('submission_method', sa.String(length=100), nullable=True),
    sa.Column('group_work', sa.Boolean(), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.Column('aligned_outcome_ids', sa.JSON(), nullable=True),
    sa.Column('has_rubric', sa.Boolean(), nullable=False),
    sa.Column('rubric_criteria', sa.JSON(), nullable=True),
    sa.Column('marking_criteria', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('resources_provided', sa.JSON(), nullable=True),
    sa.Column('feedback_method', sa.String(length=100), nullable=True),
    sa.Column('feedback_timeline_days', sa.Integer(), nullable=True),
    sa.Column('late_penalty', sa.String(length=200), nullable=True),
    sa.Column('extension_policy', sa.Text(), nullable=True),
    sa.Column('special_consideration', sa.Text(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('materials_ready', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', GUID(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_outline_id'], ['course_outlines.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_plans_course_outline_id'), 'assessment_plans', ['course_outline_id'], unique=False)
    op.create_index(op.f('ix_assessment_plans_due_week'), 'assessment_plans', ['due_week'], unique=False)
    op.create_index(op.f('ix_assessment_plans_id'), 'assessment_plans', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_plans_unit_id'), 'assessment_plans', ['unit_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('context_used', sa.JSON(), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('content_id', GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_by_id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_versions_content_id'), 'content_versions', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_versions_id'), 'content_versions', ['id'], unique=False)
    op.create_index(op.f('ix_content_versions_version_number'), 'content_versions', ['version_number'], unique=False)
    op.create_table('conversations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('course_id', GUID(), nullable=False),
    sa.Column('lrd_id', GUID(), nullable=True),
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('task_references', sa.JSON(), nullable=True),
    sa.Column('material_references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lrd_id'], ['lrds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_course_id'), 'conversations', ['course_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_lrd_id'), 'conversations', ['lrd_id'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('generation_history',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=False),
    sa.Column('content_id', GUID(), nullable=True),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('generation_type', sa.String(length=30), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('input_context', sa.JSON(), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('generation_settings', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.JSON(), nullable=True),
    sa.Column('user_rating', sa.JSON(), nullable=True),
    sa.Column('usage_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_history_content_id'), 'generation_history', ['content_id'], unique=False)
    op.create_index(op.f('ix_generation_history_generation_type'), 'generation_history', ['generation_type'], unique=False)
    op.create_index(op.f('ix_generation_history_id'), 'generation_history', ['id'], unique=False)
    op.create_index(op.f('ix_generation_history_unit_id'), 'generation_history', ['unit_id'], unique=False)
    op.create_index(op.f('ix_generation_history_user_id'), 'generation_history', ['user_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('course_id', GUID(), nullable=False),
    sa.Column('module_id', GUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('git_path', sa.String(length=500), nullable=False),
    sa.Column('current_commit', sa.String(length=40), nullable=True),
    sa.Column('content_summary', sa.JSON(), nullable=True),
    sa.Column('validation_results', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('generation_context', sa.JSON(), nullable=True),
    sa.Column('teaching_philosophy', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_course_id'), 'materials', ['course_id'], unique=False)
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_module_id'), 'materials', ['module_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('content_id', GUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answers', sa.JSON(), nullable=True),
    sa.Column('answer_explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('partial_credit', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('bloom_level', sa.String(length=20), nullable=True),
    sa.Column('learning_objective', sa.Text(), nullable=True),
    sa.Column('question_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_content_id'), 'quiz_questions', ['content_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_question_type'), 'quiz_questions', ['question_type'], unique=False)
    op.create_table('task_lists',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('lrd_id', GUID(), nullable=True),
    sa.Column('course_id', GUID(), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lrd_id'], ['lrds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_lists_course_id'), 'task_lists', ['course_id'], unique=False)
    op.create_index(op.f('ix_task_lists_id'), 'task_lists', ['id'], unique=False)
    op.create_index(op.f('ix_task_lists_lrd_id'), 'task_lists', ['lrd_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('content_id', GUID(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('plugin_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_content_id'), 'validation_results', ['content_id'], unique=False)
    op.create_index(op.f('ix_validation_results_id'), 'validation_results', ['id'], unique=False)
    op.create_index(op.f('ix_validation_results_plugin_name'), 'validation_results', ['plugin_name'], unique=False)
    op.create_index(op.f('ix_validation_results_status'), 'validation_results', ['status'], unique=False)
    op.create_table('weekly_topics',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('course_outline_id', GUID(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_type', sa.String(length=20), nullable=False),
    sa.Column('topic_title', sa.String(length=500), nullable=False),
    sa.Column('topic_description', sa.Text(), nullable=True),
    sa.Column('key_concepts', sa.JSON(), nullable=True),
    sa.Column('learning_objectives', sa.Text(), nullable=True),
    sa.Column('pre_class_modules', sa.JSON(), nullable=True),
    sa.Column('pre_class_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('pre_class_resources', sa.JSON(), nullable=True),
    sa.Column('in_class_activities', sa.JSON(), nullable=True),
    sa.Column('in_class_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('in_class_format', sa.String(length=50), nullable=True),
    sa.Column('post_class_tasks', sa.JSON(), nullable=True),
    sa.Column('post_class_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('has_assessment', sa.Boolean(), nullable=False),
    sa.Column('assessment_details', sa.Text(), nullable=True),
    sa.Column('required_readings', sa.JSON(), nullable=True),
    sa.Column('supplementary_resources', sa.JSON(), nullable=True),
    sa.Column('equipment_required', sa.Text(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('content_ready', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', GUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_outline_id'], ['course_outlines.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_topics_course_outline_id'), 'weekly_topics', ['course_outline_id'], unique=False)
    op.create_index(op.f('ix_weekly_topics_id'), 'weekly_topics', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_topics_unit_id'), 'weekly_topics', ['unit_id'], unique=False)
    op.create_index(op.f('ix_weekly_topics_week_number'), 'weekly_topics', ['week_number'], unique=False)
    op.create_table('workflow_chat_sessions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=True),
    sa.Column('course_outline_id', GUID(), nullable=True),
    sa.Column('session_name', sa.String(length=500), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('workflow_data', sa.JSON(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('stages_completed', sa.JSON(), nullable=True),
    sa.Column('decisions_made', sa.JSON(), nullable=True),
    sa.Column('pending_questions', sa.JSON(), nullable=True),
    sa.Column('generated_content_ids', sa.JSON(), nullable=True),
    sa.Column('generated_outline_id', GUID(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('pedagogy_preference', sa.String(length=50), nullable=True),
    sa.Column('complexity_level', sa.String(length=20), nullable=True),
    sa.Column('tone_preference', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('user_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_outline_id'], ['course_outlines.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_chat_sessions_course_outline_id'), 'workflow_chat_sessions', ['course_outline_id'], unique=False)
    op.create_index(op.f('ix_workflow_chat_sessions_id'), 'workflow_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_chat_sessions_unit_id'), 'workflow_chat_sessions', ['unit_id'], unique=False)
    op.create_index(op.f('ix_workflow_chat_sessions_user_id'), 'workflow_chat_sessions', ['user_id'], unique=False)
    op.create_table('unit_learning_outcomes',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=True),
    sa.Column('course_outline_id', GUID(), nullable=True),
    sa.Column('weekly_topic_id', GUID(), nullable=True),
    sa.Column('outcome_type', sa.String(length=10), nullable=False),
    sa.Column('outcome_code', sa.String(length=20), nullable=True),
    sa.Column('outcome_text', sa.Text(), nullable=False),
    sa.Column('bloom_level', sa.String(length=20), nullable=False),
    sa.Column('cognitive_processes', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('parent_outcome_id', GUID(), nullable=True),
    sa.Column('graduate_attribute_ids', sa.Text(), nullable=True),
    sa.Column('assessment_methods', sa.Text(), nullable=True),
    sa.Column('is_measurable', sa.Boolean(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('created_by_id', GUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_outline_id'], ['course_outlines.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_outcome_id'], ['unit_learning_outcomes.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['weekly_topic_id'], ['weekly_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_learning_outcomes_course_outline_id'), 'unit_learning_outcomes', ['course_outline_id'], unique=False)
    op.create_index(op.f('ix_unit_learning_outcomes_id'), 'unit_learning_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_unit_learning_outcomes_outcome_type'), 'unit_learning_outcomes', ['outcome_type'], unique=False)
    op.create_index(op.f('ix_unit_learning_outcomes_unit_id'), 'unit_learning_outcomes', ['unit_id'], unique=False)
    op.create_index(op.f('ix_unit_learning_outcomes_weekly_topic_id'), 'unit_learning_outcomes', ['weekly_topic_id'], unique=False)
    op.create_table('content_outcomes',
    sa.Column('content_id', GUID(), nullable=True),
    sa.Column('outcome_id', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['unit_learning_outcomes.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_outcomes')
    op.drop_index(op.f('ix_unit_learning_outcomes_weekly_topic_id'), table_name='unit_learning_outcomes')
    op.drop_index(op.f('ix_unit_learning_outcomes_unit_id'), table_name='unit_learning_outcomes')
    op.drop_index(op.f('ix_unit_learning_outcomes_outcome_type'), table_name='unit_learning_outcomes')
    op.drop_index(op.f('ix_unit_learning_outcomes_id'), table_name='unit_learning_outcomes')
    op.drop_index(op.f('ix_unit_learning_outcomes_course_outline_id'), table_name='unit_learning_outcomes')
    op.drop_table('unit_learning_outcomes')
    op.drop_index(op.f('ix_workflow_chat_sessions_user_id'), table_name='workflow_chat_sessions')
    op.drop_index(op.f('ix_workflow_chat_sessions_unit_id'), table_name='workflow_chat_sessions')
    op.drop_index(op.f('ix_workflow_chat_sessions_id'), table_name='workflow_chat_sessions')
    op.drop_index(op.f('ix_workflow_chat_sessions_course_outline_id'), table_name='workflow_chat_sessions')
    op.drop_table('workflow_chat_sessions')
    op.drop_index(op.f('ix_weekly_topics_week_number'), table_name='weekly_topics')
    op.drop_index(op.f('ix_weekly_topics_unit_id'), table_name='weekly_topics')
    op.drop_index(op.f('ix_weekly_topics_id'), table_name='weekly_topics')
    op.drop_index(op.f('ix_weekly_topics_course_outline_id'), table_name='weekly_topics')
    op.drop_table('weekly_topics')
    op.drop_index(op.f('ix_validation_results_status'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_plugin_name'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_content_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_task_lists_lrd_id'), table_name='task_lists')
    op.drop_index(op.f('ix_task_lists_id'), table_name='task_lists')
    op.drop_index(op.f('ix_task_lists_course_id'), table_name='task_lists')
    op.drop_table('task_lists')
    op.drop_index(op.f('ix_quiz_questions_question_type'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_content_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_materials_module_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_course_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_generation_history_user_id'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_unit_id'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_id'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_generation_type'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_content_id'), table_name='generation_history')
    op.drop_table('generation_history')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lrd_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_course_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_content_versions_version_number'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_id'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_content_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_assessment_plans_unit_id'), table_name='assessment_plans')
    op.drop_index(op.f('ix_assessment_plans_id'), table_name='assessment_plans')
    op.drop_index(op.f('ix_assessment_plans_due_week'), table_name='assessment_plans')
    op.drop_index(op.f('ix_assessment_plans_course_outline_id'), table_name='assessment_plans')
    op.drop_table('assessment_plans')
    op.drop_index(op.f('ix_lrds_id'), table_name='lrds')
    op.drop_index(op.f('ix_lrds_course_id'), table_name='lrds')
    op.drop_table('lrds')
    op.drop_index(op.f('ix_course_search_results_unit_id'), table_name='course_search_results')
    op.drop_index(op.f('ix_course_search_results_search_query'), table_name='course_search_results')
    op.drop_index(op.f('ix_course_search_results_id'), table_name='course_search_results')
    op.drop_table('course_search_results')
    op.drop_index(op.f('ix_course_outlines_unit_id'), table_name='course_outlines')
    op.drop_index(op.f('ix_course_outlines_id'), table_name='course_outlines')
    op.drop_table('course_outlines')
    op.drop_index(op.f('ix_course_modules_id'), table_name='course_modules')
    op.drop_index(op.f('ix_course_modules_course_id'), table_name='course_modules')
    op.drop_table('course_modules')
    op.drop_index(op.f('ix_contents_week_number'), table_name='contents')
    op.drop_index(op.f('ix_contents_unit_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_type'), table_name='contents')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_status'), table_name='contents')
    op.drop_index(op.f('ix_contents_parent_content_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_unit_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_units_year'), table_name='units')
    op.drop_index(op.f('ix_units_title'), table_name='units')
    op.drop_index(op.f('ix_units_status'), table_name='units')
    op.drop_index(op.f('ix_units_semester'), table_name='units')
    op.drop_index(op.f('ix_units_owner_id'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_index(op.f('ix_units_created_by_id'), table_name='units')
    op.drop_index(op.f('ix_units_code'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_category'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_id'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_code'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_courses_user_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_security_logs_user_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_user_email'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_timestamp'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_severity'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_jwt_token_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_ip_address'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_event_type'), table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index(op.f('ix_login_attempts_locked_until'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_is_locked'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempt_type'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_email_whitelist_pattern'), table_name='email_whitelist')
    op.drop_index(op.f('ix_email_whitelist_id'), table_name='email_whitelist')
    op.drop_table('email_whitelist')
    # ### end Alembic commands ###
