"""Add course LRD material and task tables

Revision ID: 914585f0dae0
Revises: f85c47472e09
Create Date: 2025-08-11 08:59:07.355684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "914585f0dae0"
down_revision: str | Sequence[str] | None = "f85c47472e09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "teaching_philosophy",
            existing_type=sa.VARCHAR(length=50),
            nullable=False,
        )
        batch_op.alter_column(
            "language_preference",
            existing_type=sa.VARCHAR(length=10),
            nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "language_preference",
            existing_type=sa.VARCHAR(length=10),
            nullable=True,
        )
        batch_op.alter_column(
            "teaching_philosophy",
            existing_type=sa.VARCHAR(length=50),
            nullable=True,
        )
    # ### end Alembic commands ###
