"""Add comprehensive university unit management schema

Revision ID: c310d61aa3e3
Revises: a16b7d51b4aa
Create Date: 2025-08-08 21:44:07.843469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.user import GUID


# revision identifiers, used by Alembic.
revision: str = "c310d61aa3e3"
down_revision: str | Sequence[str] | None = "a16b7d51b4aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("semester", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("pedagogy_type", sa.String(length=30), nullable=False),
        sa.Column("difficulty_level", sa.String(length=20), nullable=False),
        sa.Column("duration_weeks", sa.Integer(), nullable=False),
        sa.Column("owner_id", GUID(), nullable=False),
        sa.Column("created_by_id", GUID(), nullable=False),
        sa.Column("updated_by_id", GUID(), nullable=True),
        sa.Column("unit_metadata", sa.JSON(), nullable=True),
        sa.Column("generation_context", sa.Text(), nullable=True),
        sa.Column("credit_points", sa.Integer(), nullable=False),
        sa.Column("prerequisites", sa.Text(), nullable=True),
        sa.Column("learning_hours", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_units_code"), "units", ["code"], unique=False)
    op.create_index(
        op.f("ix_units_created_by_id"), "units", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_units_id"), "units", ["id"], unique=False)
    op.create_index(op.f("ix_units_owner_id"), "units", ["owner_id"], unique=False)
    op.create_index(op.f("ix_units_semester"), "units", ["semester"], unique=False)
    op.create_index(op.f("ix_units_status"), "units", ["status"], unique=False)
    op.create_index(op.f("ix_units_title"), "units", ["title"], unique=False)
    op.create_index(op.f("ix_units_year"), "units", ["year"], unique=False)
    op.create_table(
        "chat_sessions",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("unit_id", GUID(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("context_scope", sa.String(length=20), nullable=False),
        sa.Column("context_content_ids", sa.JSON(), nullable=True),
        sa.Column("context_metadata", sa.JSON(), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_sessions_id"), "chat_sessions", ["id"], unique=False)
    op.create_index(
        op.f("ix_chat_sessions_unit_id"), "chat_sessions", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_sessions_user_id"), "chat_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "contents",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=True),
        sa.Column("content_html", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("unit_id", GUID(), nullable=False),
        sa.Column("parent_content_id", GUID(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("learning_objectives", sa.JSON(), nullable=True),
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("difficulty_level", sa.String(length=20), nullable=True),
        sa.Column("prerequisites", sa.JSON(), nullable=True),
        sa.Column("generation_metadata", sa.JSON(), nullable=True),
        sa.Column("validation_metadata", sa.JSON(), nullable=True),
        sa.Column("content_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contents_id"), "contents", ["id"], unique=False)
    op.create_index(
        op.f("ix_contents_parent_content_id"),
        "contents",
        ["parent_content_id"],
        unique=False,
    )
    op.create_index(op.f("ix_contents_status"), "contents", ["status"], unique=False)
    op.create_index(op.f("ix_contents_title"), "contents", ["title"], unique=False)
    op.create_index(op.f("ix_contents_type"), "contents", ["type"], unique=False)
    op.create_index(op.f("ix_contents_unit_id"), "contents", ["unit_id"], unique=False)
    op.create_table(
        "course_search_results",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("unit_id", GUID(), nullable=False),
        sa.Column("search_query", sa.String(length=500), nullable=False),
        sa.Column("search_type", sa.String(length=50), nullable=False),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column("processed_results", sa.JSON(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("key_findings", sa.JSON(), nullable=True),
        sa.Column("source_urls", sa.JSON(), nullable=True),
        sa.Column("source_count", sa.JSON(), nullable=True),
        sa.Column("is_used_for_generation", sa.Boolean(), nullable=False),
        sa.Column("generation_context", sa.Text(), nullable=True),
        sa.Column("relevance_score", sa.JSON(), nullable=True),
        sa.Column("quality_metrics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_search_results_id"),
        "course_search_results",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_search_results_search_query"),
        "course_search_results",
        ["search_query"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_search_results_unit_id"),
        "course_search_results",
        ["unit_id"],
        unique=False,
    )
    op.create_table(
        "unit_learning_outcomes",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("bloom_level", sa.String(length=20), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_auto_generated", sa.Boolean(), nullable=False),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("validation_notes", sa.Text(), nullable=True),
        sa.Column("unit_id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_unit_learning_outcomes_bloom_level"),
        "unit_learning_outcomes",
        ["bloom_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unit_learning_outcomes_id"),
        "unit_learning_outcomes",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unit_learning_outcomes_unit_id"),
        "unit_learning_outcomes",
        ["unit_id"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("session_id", GUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("message_metadata", sa.JSON(), nullable=True),
        sa.Column("context_used", sa.JSON(), nullable=True),
        sa.Column("generation_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_chat_messages_role"), "chat_messages", ["role"], unique=False
    )
    op.create_index(
        op.f("ix_chat_messages_session_id"),
        "chat_messages",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "content_versions",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("content_id", GUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=True),
        sa.Column("content_html", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("change_description", sa.Text(), nullable=True),
        sa.Column("created_by_id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_versions_content_id"),
        "content_versions",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_versions_id"), "content_versions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_content_versions_version_number"),
        "content_versions",
        ["version_number"],
        unique=False,
    )
    op.create_table(
        "generation_history",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("unit_id", GUID(), nullable=False),
        sa.Column("content_id", GUID(), nullable=True),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("generation_type", sa.String(length=30), nullable=False),
        sa.Column("llm_provider", sa.String(length=50), nullable=False),
        sa.Column("model_used", sa.String(length=100), nullable=False),
        sa.Column("prompt_used", sa.Text(), nullable=False),
        sa.Column("input_context", sa.JSON(), nullable=True),
        sa.Column("generated_content", sa.Text(), nullable=False),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("generation_settings", sa.JSON(), nullable=True),
        sa.Column("execution_time_ms", sa.JSON(), nullable=True),
        sa.Column("user_rating", sa.JSON(), nullable=True),
        sa.Column("usage_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generation_history_content_id"),
        "generation_history",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_history_generation_type"),
        "generation_history",
        ["generation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_history_id"), "generation_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_generation_history_unit_id"),
        "generation_history",
        ["unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_history_user_id"),
        "generation_history",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "quiz_questions",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("content_id", GUID(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=20), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("correct_answers", sa.JSON(), nullable=True),
        sa.Column("answer_explanation", sa.Text(), nullable=True),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("partial_credit", sa.JSON(), nullable=True),
        sa.Column("feedback", sa.JSON(), nullable=True),
        sa.Column("difficulty_level", sa.String(length=20), nullable=True),
        sa.Column("bloom_level", sa.String(length=20), nullable=True),
        sa.Column("learning_objective", sa.Text(), nullable=True),
        sa.Column("question_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_questions_content_id"),
        "quiz_questions",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_questions_id"), "quiz_questions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_questions_question_type"),
        "quiz_questions",
        ["question_type"],
        unique=False,
    )
    op.create_table(
        "validation_results",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("content_id", GUID(), nullable=False),
        sa.Column("plugin_name", sa.String(length=100), nullable=False),
        sa.Column("plugin_version", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("score", sa.JSON(), nullable=True),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column("suggestions", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("execution_time_ms", sa.JSON(), nullable=True),
        sa.Column("validated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_validation_results_content_id"),
        "validation_results",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_validation_results_id"), "validation_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_validation_results_plugin_name"),
        "validation_results",
        ["plugin_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_validation_results_status"),
        "validation_results",
        ["status"],
        unique=False,
    )
    op.add_column(
        "users", sa.Column("institution", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("department", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("position_title", sa.String(length=255), nullable=True)
    )
    op.add_column("users", sa.Column("teaching_preferences", sa.JSON(), nullable=True))
    op.add_column("users", sa.Column("llm_config", sa.JSON(), nullable=True))
    op.add_column(
        "users", sa.Column("content_generation_context", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "content_generation_context")
    op.drop_column("users", "llm_config")
    op.drop_column("users", "teaching_preferences")
    op.drop_column("users", "position_title")
    op.drop_column("users", "department")
    op.drop_column("users", "institution")
    op.drop_index(op.f("ix_validation_results_status"), table_name="validation_results")
    op.drop_index(
        op.f("ix_validation_results_plugin_name"), table_name="validation_results"
    )
    op.drop_index(op.f("ix_validation_results_id"), table_name="validation_results")
    op.drop_index(
        op.f("ix_validation_results_content_id"), table_name="validation_results"
    )
    op.drop_table("validation_results")
    op.drop_index(op.f("ix_quiz_questions_question_type"), table_name="quiz_questions")
    op.drop_index(op.f("ix_quiz_questions_id"), table_name="quiz_questions")
    op.drop_index(op.f("ix_quiz_questions_content_id"), table_name="quiz_questions")
    op.drop_table("quiz_questions")
    op.drop_index(
        op.f("ix_generation_history_user_id"), table_name="generation_history"
    )
    op.drop_index(
        op.f("ix_generation_history_unit_id"), table_name="generation_history"
    )
    op.drop_index(op.f("ix_generation_history_id"), table_name="generation_history")
    op.drop_index(
        op.f("ix_generation_history_generation_type"), table_name="generation_history"
    )
    op.drop_index(
        op.f("ix_generation_history_content_id"), table_name="generation_history"
    )
    op.drop_table("generation_history")
    op.drop_index(
        op.f("ix_content_versions_version_number"), table_name="content_versions"
    )
    op.drop_index(op.f("ix_content_versions_id"), table_name="content_versions")
    op.drop_index(op.f("ix_content_versions_content_id"), table_name="content_versions")
    op.drop_table("content_versions")
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_role"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(
        op.f("ix_unit_learning_outcomes_unit_id"), table_name="unit_learning_outcomes"
    )
    op.drop_index(
        op.f("ix_unit_learning_outcomes_id"), table_name="unit_learning_outcomes"
    )
    op.drop_index(
        op.f("ix_unit_learning_outcomes_bloom_level"),
        table_name="unit_learning_outcomes",
    )
    op.drop_table("unit_learning_outcomes")
    op.drop_index(
        op.f("ix_course_search_results_unit_id"), table_name="course_search_results"
    )
    op.drop_index(
        op.f("ix_course_search_results_search_query"),
        table_name="course_search_results",
    )
    op.drop_index(
        op.f("ix_course_search_results_id"), table_name="course_search_results"
    )
    op.drop_table("course_search_results")
    op.drop_index(op.f("ix_contents_unit_id"), table_name="contents")
    op.drop_index(op.f("ix_contents_type"), table_name="contents")
    op.drop_index(op.f("ix_contents_title"), table_name="contents")
    op.drop_index(op.f("ix_contents_status"), table_name="contents")
    op.drop_index(op.f("ix_contents_parent_content_id"), table_name="contents")
    op.drop_index(op.f("ix_contents_id"), table_name="contents")
    op.drop_table("contents")
    op.drop_index(op.f("ix_chat_sessions_user_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_unit_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_units_year"), table_name="units")
    op.drop_index(op.f("ix_units_title"), table_name="units")
    op.drop_index(op.f("ix_units_status"), table_name="units")
    op.drop_index(op.f("ix_units_semester"), table_name="units")
    op.drop_index(op.f("ix_units_owner_id"), table_name="units")
    op.drop_index(op.f("ix_units_id"), table_name="units")
    op.drop_index(op.f("ix_units_created_by_id"), table_name="units")
    op.drop_index(op.f("ix_units_code"), table_name="units")
    op.drop_table("units")
    # ### end Alembic commands ###
