"""Replace database versioning with Git-backed content storage

Revision ID: c79a1b4d9725
Revises: 914585f0dae0
Create Date: 2025-08-15 12:53:53.293032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c79a1b4d9725'
down_revision: str | Sequence[str] | None = '914585f0dae0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite to handle constraint changes
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('git_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('current_commit', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('content_summary', sa.JSON(), nullable=True))
        batch_op.drop_column('raw_content')
        batch_op.drop_column('content')
        batch_op.drop_column('parent_version_id')
        batch_op.drop_column('version')
        batch_op.drop_column('is_latest')

    # Handle users table changes
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('teaching_philosophy',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=False)
        batch_op.alter_column('language_preference',
                   existing_type=sa.VARCHAR(length=10),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('language_preference',
                   existing_type=sa.VARCHAR(length=10),
                   nullable=True)
        batch_op.alter_column('teaching_philosophy',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_latest', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('version', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('parent_version_id', sa.CHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('content', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('raw_content', sa.TEXT(), nullable=True))
        batch_op.drop_column('content_summary')
        batch_op.drop_column('current_commit')
        batch_op.drop_column('git_path')
    # ### end Alembic commands ###
