"""Add SystemConfig model for application settings

Revision ID: d7a44128dc08
Revises: c79a1b4d9725
Create Date: 2025-08-15 13:29:39.033509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a44128dc08'
down_revision: str | Sequence[str] | None = 'c79a1b4d9725'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
