"""Add curriculum curator models

Revision ID: f85c47472e09
Revises: 9d268a7409dd
Create Date: 2025-08-11 08:57:47.139810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85c47472e09'
down_revision: str | Sequence[str] | None = '9d268a7409dd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with defaults first, then remove defaults if needed
    op.add_column('users', sa.Column('teaching_philosophy', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('language_preference', sa.String(length=10), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE users SET teaching_philosophy = 'mixed_approach' WHERE teaching_philosophy IS NULL")
    op.execute("UPDATE users SET language_preference = 'en-AU' WHERE language_preference IS NULL")

    # Now make them NOT NULL (this doesn't work in SQLite, but keeping for other DBs)
    # For SQLite, the columns will remain nullable but have values
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_preference')
    op.drop_column('users', 'teaching_philosophy')
    # ### end Alembic commands ###
