"""Add LoginAttempt model for security tracking

Revision ID: fc3324a1b32f
Revises: c310d61aa3e3
Create Date: 2025-08-08 23:42:57.671890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.user import GUID


# revision identifiers, used by Alembic.
revision: str = 'fc3324a1b32f'
down_revision: str | Sequence[str] | None = 'c310d61aa3e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('attempt_type', sa.String(length=30), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('lockout_reason', sa.String(length=200), nullable=True),
    sa.Column('first_attempt', sa.DateTime(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempt_type'), 'login_attempts', ['attempt_type'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_is_locked'), 'login_attempts', ['is_locked'], unique=False)
    op.create_index(op.f('ix_login_attempts_locked_until'), 'login_attempts', ['locked_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_attempts_locked_until'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_is_locked'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempt_type'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
